server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  # Base de datos principal (restaurantdb)
  datasource:
    restaurantdb:
      jdbc-url: jdbc:postgresql://localhost:5433/ERPRestuaranteDB
      username: postgres
      password: jose
      driver-class-name: org.postgresql.Driver
    zktecodata:
      jdbc-url: jdbc:postgresql://127.0.0.1:7496/biotime
      username: postgres
      password: Jhosep20.
      driver-class-name: org.postgresql.Driver
