server:
  port: 8080

spring:
  datasource:
    restaurantdb:
      jdbc-url: jdbc:postgresql://localhost:5433/ERPRestuaranteDB
      username: postgres
      password: jose
      driver-class-name: org.postgresql.Driver
    zktecodata:
      jdbc-url: jdbc:postgresql://127.0.0.1:7496/biotime
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
